### PR TITLE
Added Sublime Text 3 support.

### PR DESCRIPTION
**Pull request by kgantsov**

### CODE REVIEW

**Comment by Kostanos** [comment]
@kgantsov I see this repo is not supported any more. I'm using your fork to install plugin on my ST3

I got this error after installing plugin:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 71, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "FormatSQL in /home/kostya/.config/sublime-text-3/Installed Packages/SublimeFormatSQL.sublime-package", line 9
    view = self.view
                   ^
TabError: inconsistent use of tabs and spaces in indentation
found 4 files for base name Main.sublime-menu
theme loaded
```

The same error I got by installing from original repo.
Could you please fix it, so I will not need to create new fork from your's one :)

Thanks.
Kostya

**Comment by kgantsov** [comment]
Oh, I see this error too. I'm just removed ~/Library/Application Support/Sublime Text 3/Installed Packages/Format SQL.sublime-package and error was gone and plugin working right.

**Comment by Kostanos** [comment]
I don't have FormatSQL package. Only SublimeFormatSQL package from your fork. Any other idea?
These are my  packages (just upgraded to ST3 from ST2)

```
Package Control
Pretty JSON
SublimeFormatSQL
SublimePHPIntel # This one is disabled
SyncedSideBar  # This one is disabled
```

Thank you for the help!

**Comment by Kostanos** [comment]
Wow, just restarted the ST3 and the error has disappeared.
Thank you man!

**Comment by Kostanos** [comment]
@freewizard I see you are online, maybe it is better to open the new branch for ST3? I sow it on other plugins, this way you could maintain the support for ST2 for some period of time, until ST3 will not be stable.

Best and thank you for plugin,
K.

**Comment by kgantsov** [comment]
This plugin must work for ST2 and ST3. When I added ST3 support I'm checked plugin for ST2 and it's worked for me.

**Comment by Kostanos** [comment]
Perfect, thanks!

**Pull request merged**
